name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "train_pca.csv"
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn

      - name: Train, Build, and Push
        run: |
          # Train model
          python modelling.py 100 10 train_pca.csv

          # Get run_id
          RUN_ID=$(cat run_id.txt)
          echo "RUN_ID: $RUN_ID"

          # Build Docker
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "cc"

          # Login Docker Hub
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Tag and Push
          docker tag cc ${{ secrets.DOCKER_USERNAME }}/cc:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cc:latest
